service: core

provider:
  name: aws
  runtime: java8
  region: us-west-2
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "arn:aws:dynamodb:us-west-2:*"

package:
  artifact: target/scala-2.12/core-assembly-0.0.1.jar

functions:
  api:
    handler: io.github.howardjohn.core.LambdaServer$EntryPoint::handle
    events:
      - http:
          path: "{proxy+}"
          method: any
          cors: true
